# GitHub Sponsors funding file
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button

# GitHub Sponsors
github: # Add your GitHub username here if you set up GitHub Sponsors

# Open Collective
open_collective: # Add your Open Collective project name here

# Ko-fi
ko_fi: # Add your Ko-fi username here

# Tidelift
tidelift: # Add your Tidelift package name here

# Community Bridge
community_bridge: # Add your Community Bridge project name here

# Liberapay
liberapay: # Add your Liberapay username here

# IssueHunt
issuehunt: # Add your IssueHunt username here

# Otechie
otechie: # Add your Otechie username here

# LFX Crowdfunding
lfx_crowdfunding: # Add your LFX Crowdfunding project name here

# Custom URLs
custom: # Add up to 4 custom sponsorship URLs here
  # - https://paypal.me/yourusername
  # - https://www.buymeacoffee.com/yourusername