packages:
  - apps/*
  - packages/*

overrides:
  '@sveltejs/kit@<2.8.3': '>=2.8.3'
  cookie@<0.7.0: '>=0.7.0'
  devalue@<5.3.2: '>=5.3.2'
  esbuild@<=0.24.2: '>=0.25.0'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=4.5.3 <5.0.0: '>=5.4.21'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
